[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A Matrix homeserver client API."
documentation = "https://ruma.github.io/ruma/ruma/"
homepage = "https://github.com/ruma/ruma"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma"
readme = "README.md"
repository = "https://github.com/ruma/ruma"
version = "0.1.0"

[dependencies]
argon2rs = "0.2.5"
base64 = "0.2.1"
bodyparser = "0.4.1"
chrono = "0.2.25"
clap = "2.19.3"
diesel = "0.9.1"
env_logger = "0.3.5"
iron = "0.4.0"
log = "0.3.6"
macaroons = "0.3.1"
mount = "0.2.1"
persistent = "0.2.1"
plugin = "0.2.6"
r2d2 = "0.7.1"
r2d2-diesel = "0.9.0"
rand = "0.3.15"
router = "0.4.0"
ruma-events = "0.3.0"
rustc-serialize = "0.3.21"
serde = "0.8.21"
serde_derive = "0.8.21"
serde_json = "0.8.4"
serde_yaml = "0.5.0"
toml = "0.2.1"
unicase = "1.4.0"
url = "1.2.4"

[dependencies.diesel_codegen]
default-features = false
features = ["postgres"]
version = "0.9.0"

[dependencies.ruma-identifiers]
features = ["diesel"]
version = "0.6.0"

[dev-dependencies]
iron-test = "0.4.0"

[features]
default = ["swagger"]
swagger = []
