version: "2"
services:
  rust:
    image: "rumaio/ruma-dev@sha256:4c1fed70a424f50ee25d714a7dfb824bea60d085300316b6644c1181c2869f84"
    env:
      # Workaround for https://github.com/rust-lang/cargo/issues/3340
      # Can be removed if a fixed Cargo ever gets released. >:(
      SSL_CERT_FILE: "/etc/ssl/certs/ca-certificates.crt"
    links:
      - "postgres"
    volumes:
      - ".:/source"
      - "cargo_git:/root/.cargo/git"
      - "cargo_registry:/root/.cargo/registry"
  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=test"
volumes:
  cargo_git: {}
  cargo_registry: {}
